# SPDX-FileCopyrightText: 2021 TQ Tezos <https://tqtezos.com/>
#
# SPDX-License-Identifier: LicenseRef-MIT-TQ

steps:
 - label: Build Big Sur arm64 bottles
   key: build-bottles
   agents:
     queue: "arm64-darwin"
   if: build.tag =~ /^v.*/
   commands:
   - ./scripts/build-bottles.sh
   artifact_paths:
     - '*.bottle.*'

 - label: Build source packages
   key: build-source-packages
   if: build.tag =~ /^v.*-1/
   agents:
     queue: "docker"
   commands:
   - export TEZOS_VERSION="$(cat nix/nix/sources.json | jq -r '.tezos.ref' | cut -d'/' -f3)"
   - ./docker/docker-tezos-packages.sh --os ubuntu --type source
   - ./docker/docker-tezos-packages.sh --os fedora --type source
   artifact_paths:
     - ./out/*

 - label: Publish native packages
   if: build.tag =~ /^v.*-1/
   depends_on:
   - "build-source-packages"
   commands:
   - export TEZOS_VERSION="$(cat nix/nix/sources.json | jq -r '.tezos.ref' | cut -d'/' -f3)"
   - buildkite-agent artifact download "out/*" . --step build-source-packages
   - ./scripts/publish-native-packages.sh out

 - label: Add Big Sur arm64 bottle hashes to formulae
   depends_on:
   - "build-bottles"
   if: build.tag =~ /^v.*/
   commands:
   - buildkite-agent artifact download --step build-bottles "*" .
   - nix-shell ./scripts/shell.nix
       --run './scripts/sync-bottle-hashes.sh "$BUILDKITE_TAG" "Big Sur arm64"'

 - label: Attach bottles to the release
   depends_on:
   - "build-bottles"
   if: build.tag =~ /^v.*/
   commands:
   - buildkite-agent artifact download --step build-bottles "*" .
   - nix-shell ./scripts/shell.nix
       --run 'gh release upload "$BUILDKITE_TAG" *.bottle.*'

 - label: Check for new Tezos release
   if: build.source == "schedule" && build.branch == "master"
   commands:
   - nix-shell ./scripts/shell.nix --run ./scripts/update-tezos.sh
