name: Build homebrew bottles
on:
  # Run when a release is tagged
  push:
    tags:
      - "v*"
permissions:
  # Restrict GITHUB_TOKEN permissions
  contents: write
jobs:
  build-bottles:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: macos-10.15
            name: "Catalina"
          - os: macos-11
            name: "Big Sur"

    steps:
      - name: Install coreutils for macOS # for sha256sum
        run: brew install coreutils

      - name: Install GNU sed # for the other pipeline compatibility
        run: |
          brew install gnu-sed
          echo "$(brew --prefix)/opt/gnu-sed/libexec/gnubin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build bottles
        run: ./scripts/build-bottles.sh

      - name: Upload bottles to Github Actions
        uses: actions/upload-artifact@v2
        with:
          name: homebrew-bottles
          path: '*.bottle.*'

      - name: Add bottle hashes to formulae
        run: ./scripts/sync-bottle-hashes.sh "${GITHUB_REF#refs/tags/}" "${{ matrix.name }}"

      - name: Attach bottles to the release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: gh release upload "${GITHUB_REF#refs/tags/}" *.bottle.*
