name: Build homebrew bottles
on:
  # Run when a release is tagged
  push:
    tags:
      - "v*"
      - "zhenya/test-tag"
permissions:
  # Restrict GITHUB_TOKEN permissions
  contents: write
jobs:
  build-bottles:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build bottles
        # run: ./scripts/build-bottles.sh
        run: VER_PKG=v10.1-1 VER_MACOS=catalina ./scripts/build-bottles.sh

      - name: Upload bottles to Github Actions
        uses: actions/upload-artifact@v2
        with:
          name: homebrew-bottles
          path: '*.bottle.*'

      - name: Attach bottles to the release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: gh release upload "${GITHUB_REF#refs/tags/}" *.bottle.*

